package southlanesresort.seminarregistration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TrainingRegistration implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Employee Name")
   private java.lang.String employeeName;
   @org.kie.api.definition.type.Label(value = "Training")
   private java.lang.String training;

   public TrainingRegistration()
   {
   }

   public java.lang.String getEmployeeName()
   {
      return this.employeeName;
   }

   public void setEmployeeName(java.lang.String employeeName)
   {
      this.employeeName = employeeName;
   }

   public java.lang.String getTraining()
   {
      return this.training;
   }

   public void setTraining(java.lang.String training)
   {
      this.training = training;
   }

   public TrainingRegistration(java.lang.String employeeName,
         java.lang.String training)
   {
      this.employeeName = employeeName;
      this.training = training;
   }

}