package southlanesresort.seminarregistration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TrainingRegistration implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TrainingRegistration() {
    }

}