package southlanesresort.orderingcontractors;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Contractor")
   private java.lang.String contractor;
   @org.kie.api.definition.type.Label(value = "Service")
   private java.lang.String service;
   @org.kie.api.definition.type.Label(value = "Volume")
   private java.lang.Double volume;

   public ServiceOrder()
   {
   }

   public java.lang.String getContractor()
   {
      return this.contractor;
   }

   public void setContractor(java.lang.String contractor)
   {
      this.contractor = contractor;
   }

   public java.lang.String getService()
   {
      return this.service;
   }

   public void setService(java.lang.String service)
   {
      this.service = service;
   }

   public java.lang.Double getVolume()
   {
      return this.volume;
   }

   public void setVolume(java.lang.Double volume)
   {
      this.volume = volume;
   }

   public ServiceOrder(java.lang.String contractor, java.lang.String service,
         java.lang.Double volume)
   {
      this.contractor = contractor;
      this.service = service;
      this.volume = volume;
   }

}