package southlanesresort.roomreservations.newhotelroomreservation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CreditCard implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CREDITCARD_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "CREDITCARD_ID_SEQ", name = "CREDITCARD_ID_GENERATOR")
    private java.lang.Long id;

    public CreditCard() {
    }
    
    public CreditCard(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}